Search.appendIndex(
    [
                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter",
            "name": "ChordSvgExporter",
            "summary": "Transforms\u0020a\u0020chord\u0020into\u0020an\u0020SVG\u0020image.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003AtoSvg\u0028\u0029",
            "name": "toSvg",
            "summary": "Transforms\u0020the\u0020chord\u0020into\u0020an\u0020SVG\u0020image.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#method_toSvg"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003AtoRoman\u0028\u0029",
            "name": "toRoman",
            "summary": "Converts\u0020the\u0020given\u0020number\u0020to\u0020roman\u0020numerals.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#method_toRoman"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024cellSize",
            "name": "cellSize",
            "summary": "Size\u0020of\u0020a\u0020single\u0020cell\u0020in\u0020the\u0020grid.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_cellSize"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024cellOverflow",
            "name": "cellOverflow",
            "summary": "Height\u0020of\u0020overflow\u0020indication\u0020after\u0020of\u0020before\u0020the\u0020requested\u0020number\u0020of\u0020frets.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_cellOverflow"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024noteRadius",
            "name": "noteRadius",
            "summary": "Radius\u0020of\u0020the\u0020circle\u0020depicting\u0020a\u0020note.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_noteRadius"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024barreHeight",
            "name": "barreHeight",
            "summary": "Height\u0020of\u0020the\u0020barre\u0020bar.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_barreHeight"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024barreRadius",
            "name": "barreRadius",
            "summary": "Border\u0020radius\u0020of\u0020the\u0020barre\u0020bar.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_barreRadius"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024offsetIndicatorSize",
            "name": "offsetIndicatorSize",
            "summary": "Space\u0020reserved\u0020for\u0020the\u0020fret\u0020offset\u0020number.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_offsetIndicatorSize"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024offsetIndicatorMargin",
            "name": "offsetIndicatorMargin",
            "summary": "Margin\u0020between\u0020the\u0020grid\u0020and\u0020fret\u0020offset\u0020number.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_offsetIndicatorMargin"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024markSize",
            "name": "markSize",
            "summary": "Size\u0020of\u0020a\u0020string\u0020mark.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_markSize"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporter\u003A\u003A\u0024markMargin",
            "name": "markMargin",
            "summary": "Margin\u0020between\u0020the\u0020grid\u0020and\u0020string\u0020marks.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporter.html#property_markMargin"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporterInterface",
            "name": "ChordSvgExporterInterface",
            "summary": "Transforms\u0020a\u0020chord\u0020into\u0020an\u0020SVG\u0020image.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporterInterface.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Export\\ChordSvgExporterInterface\u003A\u003AtoSvg\u0028\u0029",
            "name": "toSvg",
            "summary": "Transforms\u0020the\u0020chord\u0020into\u0020an\u0020SVG\u0020image.",
            "url": "classes/Chords-Chord-Export-ChordSvgExporterInterface.html#method_toSvg"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord",
            "name": "Chord",
            "summary": "Chord\u0020of\u0020a\u0020string\u0020instrument.",
            "url": "classes/Chords-Chord-Model-Chord.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Chords-Chord-Model-Chord.html#method_getName"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003AgetAlternativeNames\u0028\u0029",
            "name": "getAlternativeNames",
            "summary": "",
            "url": "classes/Chords-Chord-Model-Chord.html#method_getAlternativeNames"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003AgetDefinition\u0028\u0029",
            "name": "getDefinition",
            "summary": "",
            "url": "classes/Chords-Chord-Model-Chord.html#method_getDefinition"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Chord-Model-Chord.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Chord\u0020name.",
            "url": "classes/Chords-Chord-Model-Chord.html#property_name"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003A\u0024alternativeNames",
            "name": "alternativeNames",
            "summary": "Alternative\u0020chord\u0020names.",
            "url": "classes/Chords-Chord-Model-Chord.html#property_alternativeNames"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\Chord\u003A\u003A\u0024definition",
            "name": "definition",
            "summary": "Chord\u0020definition.",
            "url": "classes/Chords-Chord-Model-Chord.html#property_definition"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition",
            "name": "ChordDefinition",
            "summary": "Chord\u0020definition.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AgetStrings\u0028\u0029",
            "name": "getStrings",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_getStrings"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AgetFretOffset\u0028\u0029",
            "name": "getFretOffset",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_getFretOffset"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AgetFrets\u0028\u0029",
            "name": "getFrets",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_getFrets"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AgetNotes\u0028\u0029",
            "name": "getNotes",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_getNotes"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AgetMarks\u0028\u0029",
            "name": "getMarks",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_getMarks"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AvalidateStrings\u0028\u0029",
            "name": "validateStrings",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_validateStrings"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AvalidateFrets\u0028\u0029",
            "name": "validateFrets",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_validateFrets"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AvalidateFretOffset\u0028\u0029",
            "name": "validateFretOffset",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_validateFretOffset"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AvalidateNotes\u0028\u0029",
            "name": "validateNotes",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_validateNotes"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003AvalidateMarks\u0028\u0029",
            "name": "validateMarks",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#method_validateMarks"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A\u0024strings",
            "name": "strings",
            "summary": "Number\u0020of\u0020strings.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#property_strings"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A\u0024fretOffset",
            "name": "fretOffset",
            "summary": "How\u0020many\u0020frets\u0020from\u0020the\u0020beginning\u0020to\u0020ignore.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#property_fretOffset"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A\u0024frets",
            "name": "frets",
            "summary": "Number\u0020of\u0020frets.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#property_frets"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A\u0024notes",
            "name": "notes",
            "summary": "Notes\u0020in\u0020the\u0020chord.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#property_notes"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordDefinition\u003A\u003A\u0024marks",
            "name": "marks",
            "summary": "String\u0020marks.",
            "url": "classes/Chords-Chord-Model-ChordDefinition.html#property_marks"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark",
            "name": "ChordMark",
            "summary": "String\u0020mark.",
            "url": "classes/Chords-Chord-Model-ChordMark.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordMark.html#method_getString"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordMark.html#method_getType"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordMark.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003ATYPE_MUTED",
            "name": "TYPE_MUTED",
            "summary": "Muted\u0020string.",
            "url": "classes/Chords-Chord-Model-ChordMark.html#constant_TYPE_MUTED"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003ATYPE_OPEN",
            "name": "TYPE_OPEN",
            "summary": "Open\u0020string.",
            "url": "classes/Chords-Chord-Model-ChordMark.html#constant_TYPE_OPEN"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003A\u0024string",
            "name": "string",
            "summary": "String\u0020number.",
            "url": "classes/Chords-Chord-Model-ChordMark.html#property_string"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordMark\u003A\u003A\u0024type",
            "name": "type",
            "summary": "Mark\u0020type.",
            "url": "classes/Chords-Chord-Model-ChordMark.html#property_type"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote",
            "name": "ChordNote",
            "summary": "Chord\u0020note.",
            "url": "classes/Chords-Chord-Model-ChordNote.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordNote.html#method_getString"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote\u003A\u003AgetFret\u0028\u0029",
            "name": "getFret",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordNote.html#method_getFret"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Chord-Model-ChordNote.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote\u003A\u003A\u0024string",
            "name": "string",
            "summary": "String\u0020number.",
            "url": "classes/Chords-Chord-Model-ChordNote.html#property_string"
        },                {
            "fqsen": "\\Chords\\Chord\\Model\\ChordNote\u003A\u003A\u0024fret",
            "name": "fret",
            "summary": "Fret\u0020number.",
            "url": "classes/Chords-Chord-Model-ChordNote.html#property_fret"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser",
            "name": "ChordXmlParser",
            "summary": "Chord\u00201.0\u0020XML\u0020document\u0020parser.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020the\u0020given\u0020XML\u0020document.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html#method_parse"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser\u003A\u003AparseAlternativeNames\u0028\u0029",
            "name": "parseAlternativeNames",
            "summary": "Extracts\u0020alternative\u0020chord\u0020names\u0020from\u0020the\u0020XML.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html#method_parseAlternativeNames"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser\u003A\u003AparseDefinition\u0028\u0029",
            "name": "parseDefinition",
            "summary": "Parses\u0020chord\u0020definition.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html#method_parseDefinition"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser\u003A\u003AparseNotes\u0028\u0029",
            "name": "parseNotes",
            "summary": "Extracts\u0020chord\u0020notes\u0020from\u0020the\u0020document.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html#method_parseNotes"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParser\u003A\u003AparseMarks\u0028\u0029",
            "name": "parseMarks",
            "summary": "Extracts\u0020chord\u0020marks\u0020from\u0020the\u0020document.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParser.html#method_parseMarks"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParserInterface",
            "name": "ChordXmlParserInterface",
            "summary": "Chord\u00201.0\u0020XML\u0020document\u0020parser.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParserInterface.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser\\ChordXmlParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020the\u0020given\u0020XML\u0020document.",
            "url": "classes/Chords-Chord-Parser-ChordXmlParserInterface.html#method_parse"
        },                {
            "fqsen": "\\Chords\\Exception\\InvalidXmlException",
            "name": "InvalidXmlException",
            "summary": "The\u0020input\u0020XML\u0020document\u0020is\u0020malformed.",
            "url": "classes/Chords-Exception-InvalidXmlException.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor",
            "name": "HtmlExportVisitor",
            "summary": "Transforms\u0020a\u0020song\u0020into\u0020HTML\u0020code.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AsaveHtml\u0028\u0029",
            "name": "saveHtml",
            "summary": "Returns\u0020the\u0020built\u0020HTML.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_saveHtml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitChord\u0028\u0029",
            "name": "visitChord",
            "summary": "Process\u0020a\u0020chord.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitChord"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitParagraph\u0028\u0029",
            "name": "visitParagraph",
            "summary": "Process\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitParagraph"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitRepeat\u0028\u0029",
            "name": "visitRepeat",
            "summary": "Process\u0020a\u0020repeat.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitRepeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitSong\u0028\u0029",
            "name": "visitSong",
            "summary": "Process\u0020entire\u0020song.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitSong"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitSongInfo\u0028\u0029",
            "name": "visitSongInfo",
            "summary": "Process\u0020song\u0020metadata.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitSongInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitSongLyrics\u0028\u0029",
            "name": "visitSongLyrics",
            "summary": "Process\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitSongLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitStrophe\u0028\u0029",
            "name": "visitStrophe",
            "summary": "Process\u0020a\u0020strophe.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitStropheReference\u0028\u0029",
            "name": "visitStropheReference",
            "summary": "Process\u0020a\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitStropheReference"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitVerse\u0028\u0029",
            "name": "visitVerse",
            "summary": "Process\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitVerse"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AvisitText\u0028\u0029",
            "name": "visitText",
            "summary": "Process\u0020plain\u0020text.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#method_visitText"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ACHORD_CLASSNAME",
            "name": "CHORD_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020chord\u0020element.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_CHORD_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003APARAGRAPH_CLASSNAME",
            "name": "PARAGRAPH_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_PARAGRAPH_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AREPEAT_CLASSNAME",
            "name": "REPEAT_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020repeat\u0020marker.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_REPEAT_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AREPEAT_START",
            "name": "REPEAT_START",
            "summary": "Repeat\u0020marker\u0020start.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_REPEAT_START"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AREPEAT_END",
            "name": "REPEAT_END",
            "summary": "Repeat\u0020marker\u0020end.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_REPEAT_END"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AREPEAT_COUNT_FORMAT",
            "name": "REPEAT_COUNT_FORMAT",
            "summary": "Repeat\u0020count\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_REPEAT_COUNT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003AREPEAT_COUNT_DEFAULT",
            "name": "REPEAT_COUNT_DEFAULT",
            "summary": "Default\u0020repeat\u0020count.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_REPEAT_COUNT_DEFAULT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_LABEL_CLASSNAME",
            "name": "STROPHE_LABEL_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020strophe\u0020label.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_LABEL_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_LABEL_FORMAT",
            "name": "STROPHE_LABEL_FORMAT",
            "summary": "Strophe\u0020label\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_LABEL_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_LABEL_REPEAT_FORMAT",
            "name": "STROPHE_LABEL_REPEAT_FORMAT",
            "summary": "Strophe\u0020label\u0020with\u0020repeat\u0020indicator\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_LABEL_REPEAT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_REFERENCE_FORMAT",
            "name": "STROPHE_REFERENCE_FORMAT",
            "summary": "Strophe\u0020reference\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_REFERENCE_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_REFERENCE_REPEAT_FORMAT",
            "name": "STROPHE_REFERENCE_REPEAT_FORMAT",
            "summary": "Strophe\u0020reference\u0020with\u0020repeat\u0020indicator\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_REFERENCE_REPEAT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003ASTROPHE_REFERENCE_CLASSNAME",
            "name": "STROPHE_REFERENCE_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#constant_STROPHE_REFERENCE_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003A\u0024html",
            "name": "html",
            "summary": "Lines\u0020of\u0020HTML\u0020code.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#property_html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003A\u0024row",
            "name": "row",
            "summary": "Chunks\u0020in\u0020the\u0020current\u0020line.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#property_row"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003A\u0024repeat",
            "name": "repeat",
            "summary": "Repeat\u0020count\u0020of\u0020the\u0020currently\u0020processed\u0020node.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#property_repeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\HtmlExportVisitor\u003A\u003A\u0024label",
            "name": "label",
            "summary": "Label\u0020of\u0020the\u0020currently\u0020processed\u0020strophe.",
            "url": "classes/Chords-Song-Export-HtmlExportVisitor.html#property_label"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions",
            "name": "PdfExportOptions",
            "summary": "PDF\u0020export\u0020settings.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AgetPaperSize\u0028\u0029",
            "name": "getPaperSize",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_getPaperSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AsetPaperSize\u0028\u0029",
            "name": "setPaperSize",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_setPaperSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AgetColumns\u0028\u0029",
            "name": "getColumns",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_getColumns"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AsetColumns\u0028\u0029",
            "name": "setColumns",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_setColumns"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AgetFontSize\u0028\u0029",
            "name": "getFontSize",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_getFontSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AsetFontSize\u0028\u0029",
            "name": "setFontSize",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_setFontSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AisPrintHiddenChords\u0028\u0029",
            "name": "isPrintHiddenChords",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_isPrintHiddenChords"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AsetPrintHiddenChords\u0028\u0029",
            "name": "setPrintHiddenChords",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_setPrintHiddenChords"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_getMetadata"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AsetMetadata\u0028\u0029",
            "name": "setMetadata",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method_setMetadata"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003APAPER_A4",
            "name": "PAPER_A4",
            "summary": "Paper\u0020size\u0020A4.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#constant_PAPER_A4"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003APAPER_A5",
            "name": "PAPER_A5",
            "summary": "Paper\u0020size\u0020A5.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#constant_PAPER_A5"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AFONT_SMALLER",
            "name": "FONT_SMALLER",
            "summary": "Smaller\u0020font\u0020size.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#constant_FONT_SMALLER"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AFONT_NORMAL",
            "name": "FONT_NORMAL",
            "summary": "Regular\u0020font\u0020size.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#constant_FONT_NORMAL"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003AFONT_BIGGER",
            "name": "FONT_BIGGER",
            "summary": "Larger\u0020font\u0020size.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#constant_FONT_BIGGER"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A\u0024paperSize",
            "name": "paperSize",
            "summary": "Paper\u0020size.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#property_paperSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "Number\u0020of\u0020columns.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#property_columns"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A\u0024fontSize",
            "name": "fontSize",
            "summary": "Font\u0020size.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#property_fontSize"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A\u0024printHiddenChords",
            "name": "printHiddenChords",
            "summary": "Should\u0020the\u0020output\u0020include\u0020chords\u0020marked\u0020as\u0020hidden\u0020for\u0020print\u003F",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#property_printHiddenChords"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportOptions\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "Additional\u0020metadata\u0020to\u0020include\u0020in\u0020the\u0020output.",
            "url": "classes/Chords-Song-Export-PdfExportOptions.html#property_metadata"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor",
            "name": "PdfExportVisitor",
            "summary": "Creates\u0020HTML\u0020code\u0020for\u0020conversion\u0020to\u0020PDF.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AsaveHtml\u0028\u0029",
            "name": "saveHtml",
            "summary": "Returns\u0020the\u0020built\u0020HTML.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_saveHtml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitChord\u0028\u0029",
            "name": "visitChord",
            "summary": "Process\u0020a\u0020chord.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitChord"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitParagraph\u0028\u0029",
            "name": "visitParagraph",
            "summary": "Process\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitParagraph"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitRepeat\u0028\u0029",
            "name": "visitRepeat",
            "summary": "Process\u0020a\u0020repeat.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitRepeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitSong\u0028\u0029",
            "name": "visitSong",
            "summary": "Process\u0020entire\u0020song.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitSong"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitSongInfo\u0028\u0029",
            "name": "visitSongInfo",
            "summary": "Process\u0020song\u0020metadata.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitSongInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitSongLyrics\u0028\u0029",
            "name": "visitSongLyrics",
            "summary": "Process\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitSongLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitStrophe\u0028\u0029",
            "name": "visitStrophe",
            "summary": "Process\u0020a\u0020strophe.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitStropheReference\u0028\u0029",
            "name": "visitStropheReference",
            "summary": "Process\u0020a\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitStropheReference"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitVerse\u0028\u0029",
            "name": "visitVerse",
            "summary": "Process\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitVerse"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AvisitText\u0028\u0029",
            "name": "visitText",
            "summary": "Process\u0020plain\u0020text.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#method_visitText"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AHEADER_CLASSNAME",
            "name": "HEADER_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020header\u0020element.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_HEADER_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AAUTHOR_CLASSNAME",
            "name": "AUTHOR_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020song\u0020author\u0020element.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_AUTHOR_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AMETADATA_CLASSNAME",
            "name": "METADATA_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020metadata\u0020block.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_METADATA_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ACELL_CLASSNAME",
            "name": "CELL_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020text\u0020chunk.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_CELL_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ATEXT_CLASSNAME",
            "name": "TEXT_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020plain\u0020text.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_TEXT_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AVERSE_CLASSNAME",
            "name": "VERSE_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_VERSE_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ACHORD_CLASSNAME",
            "name": "CHORD_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020chord\u0020element.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_CHORD_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003APARAGRAPH_CLASSNAME",
            "name": "PARAGRAPH_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_PARAGRAPH_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AREPEAT_CLASSNAME",
            "name": "REPEAT_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020a\u0020repeat\u0020marker.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_REPEAT_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AREPEAT_START",
            "name": "REPEAT_START",
            "summary": "Repeat\u0020marker\u0020start.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_REPEAT_START"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AREPEAT_END",
            "name": "REPEAT_END",
            "summary": "Repeat\u0020marker\u0020end.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_REPEAT_END"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AREPEAT_COUNT_FORMAT",
            "name": "REPEAT_COUNT_FORMAT",
            "summary": "Repeat\u0020count\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_REPEAT_COUNT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003AREPEAT_COUNT_DEFAULT",
            "name": "REPEAT_COUNT_DEFAULT",
            "summary": "Default\u0020repeat\u0020count.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_REPEAT_COUNT_DEFAULT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_LABEL_CLASSNAME",
            "name": "STROPHE_LABEL_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020strophe\u0020label.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_LABEL_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_LABEL_FORMAT",
            "name": "STROPHE_LABEL_FORMAT",
            "summary": "Strophe\u0020label\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_LABEL_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_LABEL_REPEAT_FORMAT",
            "name": "STROPHE_LABEL_REPEAT_FORMAT",
            "summary": "Strophe\u0020label\u0020with\u0020repeat\u0020indicator\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_LABEL_REPEAT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_REFERENCE_FORMAT",
            "name": "STROPHE_REFERENCE_FORMAT",
            "summary": "Strophe\u0020reference\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_REFERENCE_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_REFERENCE_REPEAT_FORMAT",
            "name": "STROPHE_REFERENCE_REPEAT_FORMAT",
            "summary": "Strophe\u0020reference\u0020with\u0020repeat\u0020indicator\u0020formatting\u0020string.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_REFERENCE_REPEAT_FORMAT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003ASTROPHE_REFERENCE_CLASSNAME",
            "name": "STROPHE_REFERENCE_CLASSNAME",
            "summary": "HTML\u0020class\u0020of\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#constant_STROPHE_REFERENCE_CLASSNAME"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024options",
            "name": "options",
            "summary": "Export\u0020settings.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_options"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024html",
            "name": "html",
            "summary": "Lines\u0020of\u0020HTML\u0020code.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024row",
            "name": "row",
            "summary": "Chunks\u0020in\u0020the\u0020current\u0020line.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_row"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024repeat",
            "name": "repeat",
            "summary": "Repeat\u0020count\u0020of\u0020the\u0020currently\u0020processed\u0020node.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_repeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024label",
            "name": "label",
            "summary": "Label\u0020of\u0020the\u0020currently\u0020processed\u0020strophe.",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_label"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\PdfExportVisitor\u003A\u003A\u0024hasChords",
            "name": "hasChords",
            "summary": "Does\u0020the\u0020current\u0020line\u0020have\u0020any\u0020chords\u003F",
            "url": "classes/Chords-Song-Export-PdfExportVisitor.html#property_hasChords"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongHtmlExporter",
            "name": "SongHtmlExporter",
            "summary": "Transforms\u0020song\u0020lyrics\u0020to\u0020HTML.",
            "url": "classes/Chords-Song-Export-SongHtmlExporter.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongHtmlExporter\u003A\u003AtoHtml\u0028\u0029",
            "name": "toHtml",
            "summary": "Transforms\u0020song\u0020lyrics\u0020to\u0020HTML.",
            "url": "classes/Chords-Song-Export-SongHtmlExporter.html#method_toHtml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongHtmlExporterInterface",
            "name": "SongHtmlExporterInterface",
            "summary": "Transforms\u0020song\u0020lyrics\u0020to\u0020HTML.",
            "url": "classes/Chords-Song-Export-SongHtmlExporterInterface.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongHtmlExporterInterface\u003A\u003AtoHtml\u0028\u0029",
            "name": "toHtml",
            "summary": "Transforms\u0020song\u0020lyrics\u0020to\u0020HTML.",
            "url": "classes/Chords-Song-Export-SongHtmlExporterInterface.html#method_toHtml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter",
            "name": "SongPdfExporter",
            "summary": "Transforms\u0020song\u0020into\u0020printable\u0020PDF\u0020document.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AtoPdf\u0028\u0029",
            "name": "toPdf",
            "summary": "Transforms\u0020the\u0020song\u0020into\u0020printable\u0020PDF\u0020document.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_toPdf"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AbuildText\u0028\u0029",
            "name": "buildText",
            "summary": "Creates\u0020a\u0020PDF\u0020file\u0020with\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_buildText"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AbuildTitle\u0028\u0029",
            "name": "buildTitle",
            "summary": "Creates\u0020a\u0020PDF\u0020file\u0020with\u0020song\u0020title.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_buildTitle"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AbuildHeader\u0028\u0029",
            "name": "buildHeader",
            "summary": "Creates\u0020a\u0020PDF\u0020file\u0020with\u0020song\u0020header.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_buildHeader"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AfontSizeToPoints\u0028\u0029",
            "name": "fontSizeToPoints",
            "summary": "Converts\u0020font\u0020size\u0020option\u0020to\u0020points.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_fontSizeToPoints"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AgetTempFile\u0028\u0029",
            "name": "getTempFile",
            "summary": "Returns\u0020random\u0020temporary\u0020file\u0020name.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#method_getTempFile"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003ACOLUMN_SPACE",
            "name": "COLUMN_SPACE",
            "summary": "Space\u0020between\u0020columns.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_COLUMN_SPACE"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AHEADER_HEIGHT",
            "name": "HEADER_HEIGHT",
            "summary": "Height\u0020of\u0020page\u0020header.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_HEADER_HEIGHT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AMARGIN_TOP",
            "name": "MARGIN_TOP",
            "summary": "Top\u0020page\u0020margin.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_MARGIN_TOP"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AMARGIN_BOTTOM",
            "name": "MARGIN_BOTTOM",
            "summary": "Bottom\u0020page\u0020margin.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_MARGIN_BOTTOM"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AMARGIN_LEFT",
            "name": "MARGIN_LEFT",
            "summary": "Left\u0020page\u0020margin.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_MARGIN_LEFT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003AMARGIN_RIGHT",
            "name": "MARGIN_RIGHT",
            "summary": "Right\u0020page\u0020margin.",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_MARGIN_RIGHT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporter\u003A\u003ATEMP_EXCEPTION_MESSAGE",
            "name": "TEMP_EXCEPTION_MESSAGE",
            "summary": "",
            "url": "classes/Chords-Song-Export-SongPdfExporter.html#constant_TEMP_EXCEPTION_MESSAGE"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporterInterface",
            "name": "SongPdfExporterInterface",
            "summary": "Transforms\u0020song\u0020into\u0020printable\u0020PDF\u0020document.",
            "url": "classes/Chords-Song-Export-SongPdfExporterInterface.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongPdfExporterInterface\u003A\u003AtoPdf\u0028\u0029",
            "name": "toPdf",
            "summary": "Transforms\u0020the\u0020song\u0020into\u0020printable\u0020PDF\u0020document.",
            "url": "classes/Chords-Song-Export-SongPdfExporterInterface.html#method_toPdf"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongXmlExporter",
            "name": "SongXmlExporter",
            "summary": "Saves\u0020a\u0020song\u0020as\u0020a\u0020Song\u00201.0\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Export-SongXmlExporter.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongXmlExporter\u003A\u003AtoXml\u0028\u0029",
            "name": "toXml",
            "summary": "Saves\u0020the\u0020song\u0020as\u0020a\u0020Song\u00201.0\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Export-SongXmlExporter.html#method_toXml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongXmlExporterInterface",
            "name": "SongXmlExporterInterface",
            "summary": "Saves\u0020a\u0020song\u0020as\u0020a\u0020Song\u00201.0\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Export-SongXmlExporterInterface.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\SongXmlExporterInterface\u003A\u003AtoXml\u0028\u0029",
            "name": "toXml",
            "summary": "Saves\u0020the\u0020song\u0020as\u0020a\u0020Song\u00201.0\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Export-SongXmlExporterInterface.html#method_toXml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface",
            "name": "VisitorInterface",
            "summary": "Visitor\u0020pattern\u0020for\u0020song\u0020objects.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitChord\u0028\u0029",
            "name": "visitChord",
            "summary": "Process\u0020a\u0020chord.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitChord"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitParagraph\u0028\u0029",
            "name": "visitParagraph",
            "summary": "Process\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitParagraph"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitRepeat\u0028\u0029",
            "name": "visitRepeat",
            "summary": "Process\u0020a\u0020repeat.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitRepeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitSong\u0028\u0029",
            "name": "visitSong",
            "summary": "Process\u0020entire\u0020song.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitSong"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitSongInfo\u0028\u0029",
            "name": "visitSongInfo",
            "summary": "Process\u0020song\u0020metadata.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitSongInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitSongLyrics\u0028\u0029",
            "name": "visitSongLyrics",
            "summary": "Process\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitSongLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitStrophe\u0028\u0029",
            "name": "visitStrophe",
            "summary": "Process\u0020a\u0020strophe.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitStropheReference\u0028\u0029",
            "name": "visitStropheReference",
            "summary": "Process\u0020a\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitStropheReference"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitText\u0028\u0029",
            "name": "visitText",
            "summary": "Process\u0020plain\u0020text.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitText"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\VisitorInterface\u003A\u003AvisitVerse\u0028\u0029",
            "name": "visitVerse",
            "summary": "Process\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Export-VisitorInterface.html#method_visitVerse"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor",
            "name": "XmlExportVisitor",
            "summary": "Saves\u0020a\u0020song\u0020as\u0020a\u0020Song\u00201.0\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AsaveXml\u0028\u0029",
            "name": "saveXml",
            "summary": "",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_saveXml"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitChord\u0028\u0029",
            "name": "visitChord",
            "summary": "Process\u0020a\u0020chord.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitChord"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitParagraph\u0028\u0029",
            "name": "visitParagraph",
            "summary": "Process\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitParagraph"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitRepeat\u0028\u0029",
            "name": "visitRepeat",
            "summary": "Process\u0020a\u0020repeat.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitRepeat"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitSong\u0028\u0029",
            "name": "visitSong",
            "summary": "Process\u0020entire\u0020song.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitSong"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitSongInfo\u0028\u0029",
            "name": "visitSongInfo",
            "summary": "Process\u0020song\u0020metadata.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitSongInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitSongLyrics\u0028\u0029",
            "name": "visitSongLyrics",
            "summary": "Process\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitSongLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitStrophe\u0028\u0029",
            "name": "visitStrophe",
            "summary": "Process\u0020a\u0020strophe.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitStropheReference\u0028\u0029",
            "name": "visitStropheReference",
            "summary": "Process\u0020a\u0020strophe\u0020reference.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitStropheReference"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitText\u0028\u0029",
            "name": "visitText",
            "summary": "Process\u0020plain\u0020text.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitText"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AvisitVerse\u0028\u0029",
            "name": "visitVerse",
            "summary": "Process\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#method_visitVerse"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AXML_VERSION",
            "name": "XML_VERSION",
            "summary": "Version\u0020of\u0020the\u0020XML\u0020\u0028not\u0020Song\u0029\u0020specification.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_XML_VERSION"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AXML_ENCODING",
            "name": "XML_ENCODING",
            "summary": "Document\u0020encoding.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_XML_ENCODING"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003ADTD_PUBLIC",
            "name": "DTD_PUBLIC",
            "summary": "Public\u0020DTD\u0020identifier\u0020of\u0020a\u0020Song\u00201.0\u0020document.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_DTD_PUBLIC"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003ADTD_SYSTEM",
            "name": "DTD_SYSTEM",
            "summary": "System\u0020DTD\u0020identifier\u0020of\u0020a\u0020Song\u00201.0\u0020document.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_DTD_SYSTEM"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AXML_NAMESPACE",
            "name": "XML_NAMESPACE",
            "summary": "URI\u0020of\u0020the\u0020Song\u00201.0\u0020XML\u0020schema.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_XML_NAMESPACE"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003AREPEAT_COUNT_DEFAULT",
            "name": "REPEAT_COUNT_DEFAULT",
            "summary": "Default\u0020value\u0020of\u0020\u0060count\u0060\u0020attribute\u0020of\u0020\u0060\u003Crepeat\u003E\u0060.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#constant_REPEAT_COUNT_DEFAULT"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003A\u0024dom",
            "name": "dom",
            "summary": "XML\u0020document.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#property_dom"
        },                {
            "fqsen": "\\Chords\\Song\\Export\\XmlExportVisitor\u003A\u003A\u0024fragmentStack",
            "name": "fragmentStack",
            "summary": "Current\u0020hierarchical\u0020structure\u0020of\u0020the\u0020built\u0020XML.",
            "url": "classes/Chords-Song-Export-XmlExportVisitor.html#property_fragmentStack"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord",
            "name": "Chord",
            "summary": "Chord\u0020within\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Model-Chord.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Chords-Song-Model-Chord.html#method_getName"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003AisPrint\u0028\u0029",
            "name": "isPrint",
            "summary": "",
            "url": "classes/Chords-Song-Model-Chord.html#method_isPrint"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Chord.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "Accepts\u0020the\u0020given\u0020visitor.",
            "url": "classes/Chords-Song-Model-Chord.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Chord\u0020name.",
            "url": "classes/Chords-Song-Model-Chord.html#property_name"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Chord\u003A\u003A\u0024print",
            "name": "print",
            "summary": "Should\u0020the\u0020chord\u0020be\u0020included\u0020in\u0020printed\u0020output\u003F",
            "url": "classes/Chords-Song-Model-Chord.html#property_print"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Node",
            "name": "Node",
            "summary": "Lyrical\u0020node.",
            "url": "classes/Chords-Song-Model-Node.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Node\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "Accepts\u0020the\u0020given\u0020visitor.",
            "url": "classes/Chords-Song-Model-Node.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\NodeContainer",
            "name": "NodeContainer",
            "summary": "Lyrical\u0020node\u0020containing\u0020other\u0020nodes.",
            "url": "classes/Chords-Song-Model-NodeContainer.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\NodeContainer\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-NodeContainer.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Paragraph",
            "name": "Paragraph",
            "summary": "Strophe\u0020paragraph.",
            "url": "classes/Chords-Song-Model-Paragraph.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Paragraph\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-Paragraph.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Paragraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Paragraph.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Paragraph\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-Paragraph.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Paragraph\u003A\u003A\u0024nodes",
            "name": "nodes",
            "summary": "Nodes\u0020within\u0020the\u0020paragraph.",
            "url": "classes/Chords-Song-Model-Paragraph.html#property_nodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat",
            "name": "Repeat",
            "summary": "Repeat\u0020block.",
            "url": "classes/Chords-Song-Model-Repeat.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-Repeat.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003AgetCount\u0028\u0029",
            "name": "getCount",
            "summary": "",
            "url": "classes/Chords-Song-Model-Repeat.html#method_getCount"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Repeat.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-Repeat.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003A\u0024nodes",
            "name": "nodes",
            "summary": "Repeated\u0020content.",
            "url": "classes/Chords-Song-Model-Repeat.html#property_nodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Repeat\u003A\u003A\u0024count",
            "name": "count",
            "summary": "How\u0020many\u0020times\u0020the\u0020contents\u0020should\u0020be\u0020repeated.",
            "url": "classes/Chords-Song-Model-Repeat.html#property_count"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song",
            "name": "Song",
            "summary": "Song.",
            "url": "classes/Chords-Song-Model-Song.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "",
            "url": "classes/Chords-Song-Model-Song.html#method_getInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003AgetLyrics\u0028\u0029",
            "name": "getLyrics",
            "summary": "",
            "url": "classes/Chords-Song-Model-Song.html#method_getLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Song.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-Song.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003A\u0024info",
            "name": "info",
            "summary": "Song\u0020metadata.",
            "url": "classes/Chords-Song-Model-Song.html#property_info"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Song\u003A\u003A\u0024lyrics",
            "name": "lyrics",
            "summary": "Song\u0020lyrics.",
            "url": "classes/Chords-Song-Model-Song.html#property_lyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo",
            "name": "SongInfo",
            "summary": "Song\u0020metadata.",
            "url": "classes/Chords-Song-Model-SongInfo.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongInfo.html#method_getTitle"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongInfo.html#method_getAuthor"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongInfo.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongInfo.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003A\u0024title",
            "name": "title",
            "summary": "Song\u0020title.",
            "url": "classes/Chords-Song-Model-SongInfo.html#property_title"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongInfo\u003A\u003A\u0024author",
            "name": "author",
            "summary": "Song\u0020author.",
            "url": "classes/Chords-Song-Model-SongInfo.html#property_author"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongLyrics",
            "name": "SongLyrics",
            "summary": "Song\u0020lyrics.",
            "url": "classes/Chords-Song-Model-SongLyrics.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongLyrics\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongLyrics.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongLyrics\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongLyrics.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongLyrics\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-SongLyrics.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\SongLyrics\u003A\u003A\u0024nodes",
            "name": "nodes",
            "summary": "Lyrics\u0020content.",
            "url": "classes/Chords-Song-Model-SongLyrics.html#property_nodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe",
            "name": "Strophe",
            "summary": "Strophe.",
            "url": "classes/Chords-Song-Model-Strophe.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-Strophe.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003AgetLabel\u0028\u0029",
            "name": "getLabel",
            "summary": "",
            "url": "classes/Chords-Song-Model-Strophe.html#method_getLabel"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Strophe.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-Strophe.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003A\u0024nodes",
            "name": "nodes",
            "summary": "Strophe\u0020content.",
            "url": "classes/Chords-Song-Model-Strophe.html#property_nodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Strophe\u003A\u003A\u0024label",
            "name": "label",
            "summary": "Strophe\u0020label.",
            "url": "classes/Chords-Song-Model-Strophe.html#property_label"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\StropheReference",
            "name": "StropheReference",
            "summary": "Reference\u0020to\u0020another\u0020strophe.",
            "url": "classes/Chords-Song-Model-StropheReference.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\StropheReference\u003A\u003AgetStrophe\u0028\u0029",
            "name": "getStrophe",
            "summary": "",
            "url": "classes/Chords-Song-Model-StropheReference.html#method_getStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\StropheReference\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-StropheReference.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\StropheReference\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "Accepts\u0020the\u0020given\u0020visitor.",
            "url": "classes/Chords-Song-Model-StropheReference.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\StropheReference\u003A\u003A\u0024strophe",
            "name": "strophe",
            "summary": "Referenced\u0020strophe.",
            "url": "classes/Chords-Song-Model-StropheReference.html#property_strophe"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Text",
            "name": "Text",
            "summary": "Plain\u0020text\u0020within\u0020the\u0020lyrics.",
            "url": "classes/Chords-Song-Model-Text.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Text\u003A\u003AgetText\u0028\u0029",
            "name": "getText",
            "summary": "",
            "url": "classes/Chords-Song-Model-Text.html#method_getText"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Text\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Text.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Text\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "Accepts\u0020the\u0020given\u0020visitor.",
            "url": "classes/Chords-Song-Model-Text.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Text\u003A\u003A\u0024text",
            "name": "text",
            "summary": "Text.",
            "url": "classes/Chords-Song-Model-Text.html#property_text"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Verse",
            "name": "Verse",
            "summary": "Lyrics\u0020verse.",
            "url": "classes/Chords-Song-Model-Verse.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Verse\u003A\u003AgetNodes\u0028\u0029",
            "name": "getNodes",
            "summary": "",
            "url": "classes/Chords-Song-Model-Verse.html#method_getNodes"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Verse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chords-Song-Model-Verse.html#method___construct"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Verse\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Chords-Song-Model-Verse.html#method_accept"
        },                {
            "fqsen": "\\Chords\\Song\\Model\\Verse\u003A\u003A\u0024nodes",
            "name": "nodes",
            "summary": "Verse\u0020content.",
            "url": "classes/Chords-Song-Model-Verse.html#property_nodes"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongInfoXmlParser",
            "name": "SongInfoXmlParser",
            "summary": "Song\u0020metadata\u0020XML\u0020parser.",
            "url": "classes/Chords-Song-Parser-SongInfoXmlParser.html"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongInfoXmlParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020song\u0020XML\u0020metadata.",
            "url": "classes/Chords-Song-Parser-SongInfoXmlParser.html#method_parse"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser",
            "name": "SongLyricsXmlParser",
            "summary": "Song\u0020lyrics\u0020XML\u0020parser.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parse"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AextractLabeledStrophes\u0028\u0029",
            "name": "extractLabeledStrophes",
            "summary": "Returns\u0020strophes\u0020with\u0020a\u0020label.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_extractLabeledStrophes"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseLyrics\u0028\u0029",
            "name": "parseLyrics",
            "summary": "Parses\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseStrophe\u0028\u0029",
            "name": "parseStrophe",
            "summary": "Parses\u0020a\u0020strophe.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseStrophe"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseParagraph\u0028\u0029",
            "name": "parseParagraph",
            "summary": "Parses\u0020a\u0020paragraph.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseParagraph"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseVerse\u0028\u0029",
            "name": "parseVerse",
            "summary": "Parses\u0020a\u0020verse.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseVerse"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseChord\u0028\u0029",
            "name": "parseChord",
            "summary": "Parses\u0020a\u0020chord.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseChord"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongLyricsXmlParser\u003A\u003AparseRepeat\u0028\u0029",
            "name": "parseRepeat",
            "summary": "Parses\u0020a\u0020repeat\u0020element.",
            "url": "classes/Chords-Song-Parser-SongLyricsXmlParser.html#method_parseRepeat"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParser",
            "name": "SongXmlParser",
            "summary": "Song\u00201.0\u0020XML\u0020document\u0020parser.",
            "url": "classes/Chords-Song-Parser-SongXmlParser.html"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020the\u0020given\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Parser-SongXmlParser.html#method_parse"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParser\u003A\u003AparseInfo\u0028\u0029",
            "name": "parseInfo",
            "summary": "Parses\u0020song\u0020metadata.",
            "url": "classes/Chords-Song-Parser-SongXmlParser.html#method_parseInfo"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParser\u003A\u003AparseLyrics\u0028\u0029",
            "name": "parseLyrics",
            "summary": "Parses\u0020song\u0020lyrics.",
            "url": "classes/Chords-Song-Parser-SongXmlParser.html#method_parseLyrics"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParserInterface",
            "name": "SongXmlParserInterface",
            "summary": "Song\u00201.0\u0020XML\u0020document\u0020parser.",
            "url": "classes/Chords-Song-Parser-SongXmlParserInterface.html"
        },                {
            "fqsen": "\\Chords\\Song\\Parser\\SongXmlParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020the\u0020given\u0020XML\u0020document.",
            "url": "classes/Chords-Song-Parser-SongXmlParserInterface.html#method_parse"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Export",
            "name": "Export",
            "summary": "",
            "url": "namespaces/chords-chord-export.html"
        },                {
            "fqsen": "\\Chords\\Chord",
            "name": "Chord",
            "summary": "",
            "url": "namespaces/chords-chord.html"
        },                {
            "fqsen": "\\Chords",
            "name": "Chords",
            "summary": "",
            "url": "namespaces/chords.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/chords-chord-model.html"
        },                {
            "fqsen": "\\Chords\\Chord\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/chords-chord-parser.html"
        },                {
            "fqsen": "\\Chords\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/chords-exception.html"
        },                {
            "fqsen": "\\Chords\\Song\\Export",
            "name": "Export",
            "summary": "",
            "url": "namespaces/chords-song-export.html"
        },                {
            "fqsen": "\\Chords\\Song",
            "name": "Song",
            "summary": "",
            "url": "namespaces/chords-song.html"
        },                {
            "fqsen": "\\Chords\\Song\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/chords-song-model.html"
        },                {
            "fqsen": "\\Chords\\Song\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/chords-song-parser.html"
        }            ]
);
